name: m1a-nextflow
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - catboost
  - matplotlib
  - seaborn
  - joblib
  - minimap2
  - samtools
  - f5c
  - pigz
  - pip
  - pip:
      - gseapy
